### ISSUE TITLE
platform.linux_distribution removed in Python 3.7

### ISSUE THREAD

**Issue by jayvdb** [aboutcode-org/scancode-plugins#23]
There are [three uses](https://github.com/nexB/scancode-plugins/search?q=platform.linux_distribution) of [`platform.linux_distribution`](https://docs.python.org/3.5/library/platform.html#platform.linux_distribution), which was removed in Python 3.7

**Comment by JonoYang** [comment]
@jayvdb A fix by @eclipseo has been merged into main
